## template: jinja
#cloud-config
# Minimal configuration to install CUDA toolkit on Ubuntu (Native/Cloud)

# Add NVIDIA's official repository for CUDA toolkit on Ubuntu
apt:
  sources:
    cuda:
      # NOTE: Ensure the version (e.g., ubuntu2404 or ubuntu2204) matches your OS
      source: "deb https://developer.download.nvidia.com/compute/cuda/repos/{{ v1.distro | lower }}{{ v1.distro_version | replace('.', '') }}/{{ 'sbsa' if v1.machine == 'aarch64' else 'x86_64' }}/ /"
      keyid: 3BF863CC

yum_repos:
  cuda:
    name: "NVIDIA CUDA Repository"
    baseurl: "https://developer.download.nvidia.com/compute/cuda/repos/{{ v1.distro | lower }}{{ v1.distro_version | replace('.', '')}}/{{ 'sbsa' if v1.machine == 'aarch64' else 'x86_64' }}/"
    enabled: true
    gpgcheck: true
    # NOTE: The gpgkey URL can be found on NVIDIA's official CUDA repository(https://developer.download.nvidia.com/compute/cuda/repos/<distro>/<arch>/)
    gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/{{ v1.distro | lower }}{{ v1.distro_version | replace('.', '')}}/{{ 'sbsa' if v1.machine == 'aarch64' else 'x86_64' }}/D42D0685.pub

zypper:
  repos:
    - name: cuda
      url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ v1.distro | lower }}{{ v1.distro_version | replace('.', '') }}/{{ 'sbsa' if v1.machine == 'aarch64' else 'x86_64' }}/"
      alias: cuda
      enabled: true
      gpgcheck: true
      # NOTE: The gpgkey URL can be found on NVIDIA's official CUDA repository(https://developer.download.nvidia.com/compute/cuda/repos/<distro>/<arch>/)
      gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/{{ v1.distro | lower }}{{ v1.distro_version | replace('.', '') }}/{{ 'sbsa' if v1.machine == 'aarch64' else 'x86_64' }}/D42D0685.pub

# Install the specific CUDA toolkit package
packages:
  - cuda-toolkit-13-1 # NOTE: Adjust version as needed: 12-8, 13-1, etc.
  # - cuda-drivers # Optional: Install NVIDIA drivers if needed (usually not required in cloud environments with GPU passthrough)
  # - nvidia-open # Optional: Install NVIDIA Opensource drivers if preferred over proprietary (check compatibility with your GPU and CUDA version)
